name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install packages
        run: npm install

      - name: Run lint
        run: npm run lint
